
name: tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: |
          google-chrome --version || true
          which google-chrome || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (unit + system) and generate HTML report
        run: |
          pytest -q --maxfail=1 --disable-warnings --html=report.html --self-contained-html

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
          if-no-files-found: error
